### ISSUE TITLE
C:/Users/mk/cpp-workspace/minml/  non-existent

### ISSUE THREAD

**Issue by Reginer** [MaciejKozarzewski/AlphaGomoku#10]
Hello , MK.
Can I get the dependencies under this folder?

**Comment by MaciejKozarzewski** [comment]
Hi, 
AlphaGomoku uses neural network backend library which is my other project: https://github.com/MaciejKozarzewski/minml
You have to build it first and then specify path to it when building AG. The path you ask about is simply a path at my machine which I accidently commited to github.

Note that if you really want to build AG from source you enter unexplored areas. If you encounter problems with minml project, post an issue out there rather than here.
