### ISSUE TITLE
New function

### ISSUE THREAD

**Issue by nguyencongminh090** [MaciejKozarzewski/AlphaGomoku#3]
I'm thinking about adding a new function named "full_time_analyze". I need this function to analyze a position, sometimes I just wanna analyze to find the best solution, not play a full game, without this, I have to set a very long time, about 14400 seconds (4 hours) to let the engine thinking 1 move in 10 minutes. What do you think about this?

**Comment by MaciejKozarzewski** [comment]
In theory the 'PONDER x' command does exactly that - it runs the search for x milliseconds. The only difference between it and other Gomocup protocol commands is that it doesn't explicitly return the best move. But it can still be extracted from INFO message, or logfile.
But the problem is that in Gomocup protocol you can't specify board position without requesting the engine to find best move. Something solved for example in YixinBoard 'yxboard' command. Since the support for YixinBoard most likely will be added in the future, I won't fix this issue now. Especially that you can work around this issue by setting very large _timeout_match_ and _time_left_ (the order of int32 max value) and controlling the exact search time with _timeout_turn_.

**Comment by nguyencongminh090** [comment]
Okay, thanks
