### ISSUE TITLE
Flood in log in Piskvork GUI (multiple empty lines)

### ISSUE THREAD

**Issue by garry-ut99** [MaciejKozarzewski/AlphaGomoku#9]
It happens when playing Human vs AI, doesn't happen when AI vs AI, 
(Piskvork 8.9.2 + AlphaGomoku 5.7.0 CPU version (1 core) ) :

![flood](https://github.com/MaciejKozarzewski/AlphaGomoku/assets/72945564/686bcec5-ecbe-403e-87b1-d2d5bc9807a9)

**Comment by MaciejKozarzewski** [comment]
Those lines are responses to the 'INFO evaluate X,Y' commands that you are sending. If you don't want do do it, uncheck option 'send info to evaluate x,y' in piskvork.
Empty lines are simply responses for moves that are not present in the search tree, but they must be sent. Otherwise you wouldn't know if the requested move is not in the tree or the engine didn't send any response.

**Comment by garry-ut99** [comment]
Also found in piskvork.txt manual 

> - Send info evaluate x,y: it is used for debugging your AI. This command is sent when the mouse is moving, but only when it's human's turn.

**Comment by MaciejKozarzewski** [comment]
My implementation assumes that this command is sent during the search time. Reopening this as a bug.

**Comment by MaciejKozarzewski** [comment]
Should be fixed in the 5.8.1 version.
